# Generated by Django 4.2.30 on 2026-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_filename', models.CharField(max_length=255)),
                ('cv_text', models.TextField()),
                ('job_description', models.TextField()),
                ('match_score', models.IntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
